### ISSUE TITLE
2.1.1 - Search for content by colloquial name (Advanced search)

### ISSUE THREAD

**Issue by janahoffmann** [gbhl/bhl-europe#74] opened 2011-06-24 12:38 UTC
Search with colloquial name:
Search in metadata (titles, etc.) and OCR 
or translate Latin names found by uBio into colloquial names by other web services (search term amplification)

Precondition: index latin names, and colloquial names (coordinates) in metadata, e.g. title, OCR, integrate taxonomic intelligence web services, e.g. Sp2000, PESI, ...

Related issue: #185, #187

**Comment by wkollernhm** [comment] 2011-08-11 10:08
I've just pushed the names_lookup module which provides the functionality to search for scientific names using a common names. Details on this will be published to the Tech List.

I've re-assigned this issue to Lola in order to make sure that the integration of this service into the actual search process can take place.

**Comment by lobajuluwa** [comment] 2011-08-11 11:57
New project task Issue (#187) Integration of webservices for names_lookup module. The integration of this service into the actual search process needs to be completed by AIT. 
Feature cannot be Closed for testing until module has been integrated into search process.
Assigned to AIT's Project Assistant.

**Comment by lobajuluwa** [comment] 2011-08-24 14:01
Wolfgang will now be doing the integration work reqd for the names_lookup module into the overall system, upon his return from hols.
milestone ytbd.
@wkollernhm
@janahoffmann

**Comment by lobajuluwa** [comment] 2011-10-13 09:23
Same as Issue (#76)

**Comment by wkollernhm** [comment] 2011-10-27 13:13
We still need clarification on which fields we want to enable the colloquial name searching for? Only for scientific name?

**Comment by wkollernhm** [comment] 2011-11-18 09:37
Searching for common names is now possible using a own index field (which is a copy of the scientific name field). Thus the user will have to select common names in the target field drop down in order to search for a scientific name translated from a common name.

**Comment by JiriFrank** [comment] 2012-01-17 14:06
2.1.1 - Search for content by colloquial name (Advanced search)

COR number: 2.1.1
Testing platform: http://bhl-test.nhm.ac.uk/portal/
Function: Advanced search

Description:

Search with colloquial name:
Search in metadata (titles, etc.) and OCR 
or translate Latin names found by uBio into colloquial names by other web services (search term amplification)

„expand search“ function

@AnneSch
@AntonioGVH
@fwelter
@grahamhrbge1670
@heimor
@HenningScholz
@JFTester
@JiriFrank
@LarissaS
@RalfH

**Comment by RalfH** [comment] 2012-01-18 16:31
Does not work.

UBio gives bird skin lice for Epidermoptidae (part of one title) but it is not found.

-----Ursprüngliche Nachricht-----
Von: JiriFrank [mailto:reply@reply.github.com] 
Gesendet: Dienstag, 17. Januar 2012 15:07
An: Hand, Ralf
Betreff: Re: [bhle] 2.1.1 - Search for content by colloquial name (Advanced search) (#74)

2.1.1 - Search for content by colloquial name (Advanced search)

COR number: 2.1.1
Testing platform: http://bhl-test.nhm.ac.uk/portal/
Function: Advanced search

Description:

Search with colloquial name:
Search in metadata (titles, etc.) and OCR 
or translate Latin names found by uBio into colloquial names by other web services (search term amplification)

"expand search" function

@AnneSch
@AntonioGVH
@fwelter
@grahamhrbge1670
@heimor
@HenningScholz
@JFTester
@JiriFrank
@LarissaS
@RalfH

---

**Comment by grahamhrbge1670** [comment] 2012-01-18 17:29
Can't get this to work.

Graham

**Comment by JiriFrank** [comment] 2012-01-19 10:50
2.1.1 - Search for content by colloquial name (Advanced search)

COR number: 2.1.1
Testing platform: http://bhl-test.nhm.ac.uk/portal/
Function: Advanced search

Description:

Search with colloquial name:
Search in metadata (titles, etc.) and OCR 
or translate Latin names found by uBio into colloquial names by other web services (search term amplification)

„expand search“ function

@AntonioGVH
@fwelter
@LarissaS

**Comment by HenningScholz** [comment] 2012-01-19 21:33
The metadata have no scientifc name (genus, species). I expect the expanded search to work only in these cases. So no surprise it does not work. Search in OCR only works if the word is in the text. Search term expansion does not work in OCR search, as far as I know.

---

Von: JiriFrank [mailto:reply@reply.github.com]
Gesendet: Di 17.01.2012 15:06
An: Scholz, Henning
Betreff: Re: [bhle] 2.1.1 - Search for content by colloquial name (Advanced search) (#74)

2.1.1 - Search for content by colloquial name (Advanced search)

COR number: 2.1.1
Testing platform: http://bhl-test.nhm.ac.uk/portal/
Function: Advanced search

Description:

Search with colloquial name:
Search in metadata (titles, etc.) and OCR
or translate Latin names found by uBio into colloquial names by other web services (search term amplification)

"expand search" function

@AnneSch
@AntonioGVH
@fwelter
@grahamhrbge1670
@heimor
@HenningScholz
@JFTester
@JiriFrank
@LarissaS
@RalfH

---

**Comment by AntonioGVH** [comment] 2012-01-20 15:16
I do not understand properly the way to test this feature.
I asume 'advance search' and then selecting words in title, abstract, etc?

Quoting JiriFrank:

**Comment by AnneSch** [comment] 2012-01-23 11:22
Did not get this to work. Similar results as Ralf H. 

-----Ursprüngliche Nachricht-----
Von: JiriFrank [mailto:reply@reply.github.com] 
Gesendet: Dienstag, 17. Januar 2012 15:07
An: Scholz, Annemarie
Betreff: Re: [bhle] 2.1.1 - Search for content by colloquial name (Advanced search) (#74)

2.1.1 - Search for content by colloquial name (Advanced search)

COR number: 2.1.1
Testing platform: http://bhl-test.nhm.ac.uk/portal/
Function: Advanced search

Description:

Search with colloquial name:
Search in metadata (titles, etc.) and OCR 
or translate Latin names found by uBio into colloquial names by other web services (search term amplification)

"expand search" function

@AnneSch
@AntonioGVH
@fwelter
@grahamhrbge1670
@heimor
@HenningScholz
@JFTester
@JiriFrank
@LarissaS
@RalfH

---

**Comment by JiriFrank** [comment] 2012-01-24 15:32
Same for me. I tried "Plants" for Plantae, which is included in bookes, but get 0 results. Tested also on nhm.int.

Is this service implemented? What is the right method to test it?

@wkollernhm

**Comment by JiriFrank** [comment] 2012-01-24 15:49
Tested with "Common names" and "Scientific names"
tested term: Plants
Matches for: Plants expanded to: \"Plantae\" OR \"Plants\" (10) Common name
0 results - but the books with reporting Plantae as scientific names are in content

@wkollernhm

**Comment by wkollernhm** [comment] 2012-01-25 09:53
Searching by a colloquial name looks up the colloquial name using the CoL & PESI webservices. The received scientific names are then used to search against the list of scientific names found in each book.
Therefor this feature does not search in the title but rather is another way to search against the list of scientific names.

Hope it is now more clear, how this feature works.

**Comment by JiriFrank** [comment] 2012-01-25 10:12
Thank you Wolfgang, 

but did you read the last comment? It was tested in Scientific name and Common name, not on title.

Best,
Jiri

---

Mgr. Jiri Frank
BHL-Europe WP5 Project Manager
Open Up! WP8
National Museum
Vaclavske namesti 68
115 79 Prague 1
Czech Republic
tel.: +420 281 029 199
email: jiri_frank@nm.cz

----- Původní zpráva -----

**Comment by wkollernhm** [comment] 2012-01-30 11:41
I did indeed read the last comment.

I just tried to point out more clearly how this feature works.

Can you please point out which PID the document has which has Plantae in its scientific names list?

A raw query to Solr returns zero hits!

**Comment by wkollernhm** [comment] 2012-01-30 11:52
After investigating on this I can confirm that a search to "Plantae*" returns hits. Maybe this is an Solr issue

@akohlbecker can you please clarify why solr needs a wildcard search even if the scientific name is just plantae (example PID: bhle:19)

**Comment by akohlbecker** [comment] 2012-01-31 11:32
The issue that "Plantae" is not found is strongly related to the Umlaut problem described in #288, so this is ticket can be closed since it is a duplicate, for an in depth description of the technical details please refer to #288

**Closed as completed by akohlbecker** 2012-01-31 11:32 UTC
Labels: feature, critical, Nov 2011, web services
