### ISSUE TITLE
OLEF datastream in METS is mal-formed

### ISSUE THREAD

**Issue by zhengl** [gbhl/bhl-europe#388] opened 2012-03-23 00:57 UTC
In METS of 'book' objects, OLEF metadata is enclosed by a redundant <olef> tag, e.g.

< olef>
< olef:olef xmlns:olef="http://www.bhl-europe.eu/bhl-schema/v0.3/">
< olef:element>
......
< /olef:olef>
< /olef>

**Comment by mindcatch-com** [comment] 2012-03-23 16:04
right.
this is a re-generating bug and is now fixed.

**Closed as completed** 2012-03-26 09:27 UTC
Labels: bug, Pre-Ingest and OLEF, Critical_P1

**Comment by wkollernhm** [comment] 2012-03-30 06:05
Confirmed - this seems to be fixed now.
