### ISSUE TITLE
4.1.7 - Show BHL news (Community portal)

### ISSUE THREAD

**Issue by janahoffmann** [gbhl/bhl-europe#110] opened 2011-06-24 13:37 UTC
News feed (RSS): BHL Blog, Tweets, Facebook
Display on main page

**Comment by janahoffmann** [comment] 2011-06-24 14:43
previous comments @akohlbecker
RSS feeds issued from twitter, facebook etc are to be displayed on the portal front page in a "news" box.
This can be accomplished by making use of the Drupal aggregator module.
The news box will be placed initially in the left side bar.

List of potential feeds to be included:
- http://twitter.com/BHLEurope
- http://www.facebook.com/pages/BHL-Europe/151086001600041
- http://bhleurope.blogspot.com/
  A compilation of different feed sources is http://www.netvibes.com/bhl-europe#Projects

Further reading:
- http://support.twitter.com/groups/31-twitter-basics/topics/111-features/articles/15361-how-to-find-your-rss-feed

**Comment by akohlbecker** [comment] 2011-07-19 10:19
The news block has been added to the right sidebar.

It aggregates the  following feeds: 
- BHL Europe - Blog: http://bhleurope.blogspot.com/feeds/posts/default
- BHL Europe - Tweets: http://search.twitter.com/search.atom?q=+BHLEurope

Adding the Facebook feeds is more complicated, see  http://www.staze.org/facebooks-crappy-rssatom-feed/ for a solution.

**Comment by akohlbecker** [comment] 2011-07-19 10:26
In contrast to the problems with the facebook rss feeds mentioned in the article posted above adding atom feeds is straight forward: 
- http://www.facebook.com/feeds/page.php?format=atom10&id=151086001600041

**Comment by akohlbecker** [comment] 2011-07-19 10:37
fixed by commit d86414227f1a04ec0409

**Comment by akohlbecker** [comment] 2011-07-19 15:13
The summaries of the news items are broken, this seems to be due to the following bug: http://drupal.org/node/474812 ( Feed aggregator strips characters from rss feeds, breaking summaries and links )

**Comment by akohlbecker** [comment] 2011-07-20 09:09
Further investigation turned out that this problem seems to be caused by a bug in the php xml parser. 
The bug seems to affect some older versions of php:
- https://bugs.php.net/bug.php?id=45996
- http://www.phpfreaks.com/forums/index.php?topic=269015.0 

I'll will test with a more recent version of php ...

**Comment by akohlbecker** [comment] 2011-07-20 16:35
It is in fact fixed in later versions of php, tested with php 5.3.2. Although it is necessary to refresh the feed items (?q=admin/config/services/aggregator) before going to production. I'll delete them all for now: bdf463a6fdf207044f0b

**Comment by JiriFrank** [comment] 2011-07-28 13:11
Ready for testing? The RSS is already omplemented on the portal.

**Comment by janahoffmann** [comment] 2011-07-28 14:47
ready for testing but are all news feed included now, also facebook, twitter and the blog? @akohlbecker

possible to add feed to favourites - o.k.
feeds are displayed correctly - however, no feeds on BHL E blog, twitter or facebook visible

There are actual news on BHLE facebook, twitter, etc. but not displayed here, seems not to work in terms of display of news

**Comment by JiriFrank** [comment] 2011-08-01 08:32
Testing of feature 4.1.7 - Show BHL news

Feature description from the Catalogue of user requirements:

Show news feed (RSS)/ 'news'
BHL blog/ forum
'about us'

What to be displayed on main page?

Testers:
@AntonioGVH
@fwelter
@heimor
@janahoffmann
@JFTester
@JiriFrank
@LarissaS

**Comment by JiriFrank** [comment] 2011-08-03 08:30
Testing of feature 4.1.7 - Show BHL news

Feature description from the Catalogue of user requirements:

Show news feed (RSS)/ 'news'
BHL blog/ forum
'about us'

What to be displayed on main page?

Testers:
@fwelter

**Comment by akohlbecker** [comment] 2011-08-09 12:24
replying to @janahoffmann (comment from July 28):

The new portal installation at http://bhl-alexandria.nhm.ac.uk/bhle_dev_portal/ , which is now up to date with all changes, is showing the latest posts from twitter, facebook, etc.

**Comment by LarissaS** [comment] 2011-08-11 12:45
Jiri,
Is it necessary  to subscribe for RSS?

Greetings
Larissa

-----Original Message-----

**Comment by AntonioGVH** [comment] 2011-08-12 15:33
Not available now ot I have not beeen able to see it.

A

Quoting JiriFrank:

**Comment by fwelter** [comment] 2011-08-12 17:40
4.1.7   BHL news

I did not know where to click for this feature. seems that it has not
yet been installed on the portal.

Francisco

---

F. Welter-Schultes
Zoologisches Institut, Berliner Str. 28, D-37073 Goettingen
Phone +49 551 395536, Fax +49 551 395579
http://www.gwdg.de/~fwelter
http://www.animalbase.org

**Comment by JiriFrank** [comment] 2011-08-16 23:30
The function is implemented in development portal as Andreas mentioned. It need to be styled and designed for the new portal template. This is task for me and IT4Care and it will be related with the Look and Feel feature and with the Portal design development.

**Comment by janahoffmann** [comment] 2011-08-17 09:47
@jirifrank
The function is there, yes, but the reshaping needs to me encoded in another task. Either report is as a bug of the feature or create a new task (project tasks): web design of portal (including this task)

**Comment by janahoffmann** [comment] 2011-10-24 12:29
@jirifrank
So, this is then part of #104 (web design of portal).

**Comment by JiriFrank** [comment] 2012-01-17 14:29
4.1.7 - Show BHL news (Community portal)

COR number: 4.1.7
Testing platform: http://bhl-test.nhm.ac.uk/portal/
Function: Front page

Description:

News feed (RSS): BHL Blog, Tweets, Facebook
Display on main page

@AnneSch
@AntonioGVH
@fwelter
@grahamhrbge1670
@heimor
@HenningScholz
@JFTester
@JiriFrank
@LarissaS
@RalfH

**Comment by RalfH** [comment] 2012-01-18 13:41
No problems found.

-----Ursprüngliche Nachricht-----
Von: JiriFrank [mailto:reply@reply.github.com] 
Gesendet: Dienstag, 17. Januar 2012 15:29
An: Hand, Ralf
Betreff: Re: [bhle] 4.1.7 - Show BHL news (Community portal) (#110)

4.1.7 - Show BHL news (Community portal)

COR number: 4.1.7
Testing platform: http://bhl-test.nhm.ac.uk/portal/
Function: Front page

Description:

News feed (RSS): BHL Blog, Tweets, Facebook
Display on main page

@AnneSch
@AntonioGVH
@fwelter
@grahamhrbge1670
@heimor
@HenningScholz
@JFTester
@JiriFrank
@LarissaS
@RalfH

---

**Comment by JiriFrank** [comment] 2012-01-19 10:57
4.1.7 - Show BHL news (Community portal)

COR number: 4.1.7
Testing platform: http://bhl-test.nhm.ac.uk/portal/
Function: Front page

Description:

News feed (RSS): BHL Blog, Tweets, Facebook
Display on main page

@AntonioGVH
@fwelter
@LarissaS

**Comment by LarissaS** [comment] 2012-01-19 12:21
Ok, but are these news about BHL or also about biodiversity (smallest frog from Papua)? 

-----Original Message-----

**Comment by HenningScholz** [comment] 2012-01-19 22:42
Works fine, although the click on the posts should automatically open in a new tab or window to not leave the portal.

---

Von: JiriFrank [mailto:reply@reply.github.com]
Gesendet: Di 17.01.2012 15:29
An: Scholz, Henning
Betreff: Re: [bhle] 4.1.7 - Show BHL news (Community portal) (#110)

4.1.7 - Show BHL news (Community portal)

COR number: 4.1.7
Testing platform: http://bhl-test.nhm.ac.uk/portal/
Function: Front page

Description:

News feed (RSS): BHL Blog, Tweets, Facebook
Display on main page

@AnneSch
@AntonioGVH
@fwelter
@grahamhrbge1670
@heimor
@HenningScholz
@JFTester
@JiriFrank
@LarissaS
@RalfH

---

**Comment by grahamhrbge1670** [comment] 2012-01-20 15:01
Works fine.  Also checked out the contact us functionality and it works too. Particularly like the send copy of your e-mail to self function.

**Comment by JiriFrank** [comment] 2012-01-25 11:24
Works fine.

@LarissaS 
Yes these are just BHLE news. Will be changed also to BHL US after BHLE project will ends.

@HenningScholz 
We can try opening windows in new tab as a default is against the www rules and could be blocked. Anyway if the user is on our social media site, there are links back to portal or he can go easily back or open the link in new tab depending on functions of his browser.

**Closed as completed by JiriFrank** 2012-01-25 11:24 UTC
Labels: feature, critical, Aug 2011
