### ISSUE TITLE
1.1.4 - Search with words including diacritic characters (Simple Search)

### ISSUE THREAD

**Issue by JiriFrank** [gbhl/bhl-europe#176] opened 2011-07-29 14:35 UTC
Searching by terms ae, oe, ue, etc. is not working. The results for example for Löwe includes many different records included just parts of this word or even many of them doesn’t correspond with searching term. The user will get completely different result than he expected.

For more details see last comments in Issue #36 

In the case with term Küsten:
Küsten: in this case is problem in metadata, because the term Küsten on the website is not written in metadata properly but it is probably problem of OCR. Same problems are on BHL portal, especially by old books. It looks similar, but when you export or edit the metadata, the term is different. Copy past tactic is just copy the wrong term from the metadata to the searching option. It is actually not a bug of the portal but of the metadata them self. This function mainly depends on the quality of metadata and OCR. Metadata are often created from the book OCR data (several examples on BHL US).

**Comment by akohlbecker** [comment] 2011-08-15 08:18
Hi Jiri, shouldn't we close this ticket, since is obviously is a duplicate of  #36 ?

**Comment by JiriFrank** [comment] 2011-08-15 10:45
Hi Andreas,

#36 is a feature, but this issue #176 is a bug, related with that feature. It is not duplication. Bugs have their own issues, because one feature could heave more than one bug. When the all bugs related with concrete feature are fixed, the feature is completely done and will be close.

**Comment by akohlbecker** [comment] 2011-08-15 11:53
Ok, Jiri, thanks for clarifying this.

In the description of this ticket you are writing that the "Küsten"-problem is a problem with metadata or OCR and that the same problem exist within the BHL Portal (http://www.biodiversitylibrary.org/), I cannot reproduce it there. Could you give an example?

**Comment by akohlbecker** [comment] 2011-08-16 12:24
Using the MappingCharFilterFactory seems to be suitable approach to solve this issue ( http://lucene.apache.org/solr/api/org/apache/solr/analysis/MappingCharFilterFactory.html ) it would have to be applied during indexing and before sending the query to Solr.

**Comment by akohlbecker** [comment] 2011-08-16 12:52
The MappingCharFilterFactory is already being used in both solr cores, the mapping configuration files are:
- portal/drupal-ait/solr/core1/conf/mapping-ISOLatin1Accent.txt
- portal/drupal-ait/solr/core2/conf/mapping-ISOLatin1Accent.txt

The character mappings are configured by now in the following way: Ä => A
So a search using "Apfel" as query term would find also "Äpfel", however if we now would normalize Ä to AE 
"Apfel" would no futher match to "Äpfel" since Äpfel would be indexed as "AEpfel". 

A more sofisticated solution is needed!

**Comment by akohlbecker** [comment] 2011-08-16 15:26
I did some investigation regarding the "Küsten"-problem: The ü is not a single unicode character (U+00FC Latin Small Letter U with diaeresis) but a combination of 
U+0075 Latin Small Letter Uand  U+0308 COMBINING DIAERESIS 
The MappingCharacterFilter with mapping-ISOLatin1Accent.txt is not able to normalise combining diacritics. 
Proper normalisation of combining diacritics has been identifies as a problem in solr https://issues.apache.org/jira/browse/LUCENE-1343 and is solved in version 3.1 by introducing the UnicodeNormalizationFilter

In current versions of solr there is a more recent replacement for this filter, the **ICUNormalizer2FilterFactory** ( http://wiki.apache.org/solr/AnalyzersTokenizersTokenFilters#solr.ICUNormalizer2FilterFactory ) it supports all Unicode Normalization Forms ( http://unicode.org/reports/tr15/ )

**Comment by JiriFrank** [comment] 2011-08-16 20:21
Great job Andreas. If we fix the searching with exact phrase for example for – “Äpfel” the result will be really just Äpfel and not also Apfel, it will be great. This problem is related with reported bug #177. In case when I am searching “Král” and the result is for “Kral” which have different meaning.

Sorry for my late response about the “Künste“ ,you have already find out the problem. Exactly the ü is not in several cases the single unicode character. The BHL-US case is, if you are looking in to the OCR, from where are the metadata in some cases used, you can see, that the ¨ (double dot) is moved right a little. This problem is often in old Latin or German books and rise form the OCR. The ¨ have in this case different code.

**Comment by akohlbecker** [comment] 2011-10-07 15:10
fixed but not ready to test

**Closed as completed by akohlbecker** 2011-10-07 15:10 UTC
Labels: bug, critical, Solr Search Facilities
