### ISSUE TITLE
Integration of the viaf_lookup module into the search process.

### ISSUE THREAD

**Issue by lobajuluwa** [gbhl/bhl-europe#185] opened 2011-08-04 09:27 UTC
The VIAF module is fully working  -  AIT will need to integrate the function call into their search process.
 Please refer to last comments in previous Issue (#76) for latest updates.

**Comment by wkollernhm** [comment] 2011-09-06 06:43
This is now a duplicate of #76 - hence I will close it.

**Closed as completed by wkollernhm** 2011-09-06 06:43 UTC
Labels: critical, project task, Aug 2011
